name: coopbank_pesalink
description: Dart package for consuming Co-op bank Pesalink API
version: 0.0.1
homepage: https://github.com/EddieKamau/coopbank_pesalink
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
